name: Run Container and Execute Tests ubuntu-native

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-in-ubuntu-container:
    runs-on: ubuntu-latest
    container:
      image:  ubuntu:latest

    steps:
      - name: Set up Python and Install Dependencies
        run: |
          apt update -y
          apt-get install -y python3 python3-pip python3-venv git wget
          apt install nvidia-cuda-toolkit -y
          apt install libnccl2 libnccl-dev -y
          apt install libcudnn9-cuda-12 -y
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          dpkg -i cuda-keyring_1.1-1_all.deb
          apt-get update -y

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-tags: false
          show-progress: true
          lfs: false
          submodules: true
          set-safe-directory: true

      - name: Check the current working directory
        run: |
          echo "Current directory: $(pwd)"
          ls -l ./test/script

      - name: Ensure script has execute permissions
        run: chmod +x /__w/FlagCX/FlagCX/test/script/auto_script.sh

      - name: Run Auto Test Script in Container
        run: |
          cd /__w/FlagCX/FlagCX
          ./test/script/auto_script.sh

